-- Hyprland Lua config. See https://wiki.hypr.land/configuring/

------------------
---- ENVS ----
------------------

require("envs")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/configuring/core/monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- Machine-local monitor layout (generated by nwg-displays, not in dotfiles)
pcall(require, "monitors")

---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "rofi -show drun -show-icons"
local browser     = "firefox"
local messenger   = "signal-desktop"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd(terminal)
    hl.exec_cmd(browser)

    hl.exec_cmd("wl-paste --type text --watch cliphist store")  -- Stores only text data
    hl.exec_cmd("wl-paste --type image --watch cliphist store") -- Stores only image data
end)

---------------------
---- PERMISSIONS ----
---------------------

-- See https://wiki.hypr.land/configuring/core/advanced-configuration/permissions/
-- Not reloaded on-the-fly; requires a Hyprland restart.
hl.config({ ecosystem = { enforce_permissions = true } })
hl.permission({ binary = "/usr/(bin|local/bin)/(grim|hyprshot)",                type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/bin/hyprctl",                                     type = "plugin",     mode = "deny" })

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/configuring/core/config-options/
hl.config({
    general = {
        gaps_in  = 2,
        gaps_out = 2,

        border_size = 2,

        col = {
            active_border   = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/configuring/extra/tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },

        blur = {
            enabled  = false,
            size     = 3,
            passes   = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    -- See https://wiki.hypr.land/configuring/layouts/dwindle-layout/
    dwindle = {
        preserve_split = true, -- You probably want this
        force_split    = 2,    -- Always split on the right
    },

    -- See https://wiki.hypr.land/configuring/layouts/master-layout/
    master = {
        new_status = "master",
    },

    binds = {
        workspace_back_and_forth = true, -- SUPER+N on workspace N jumps back to the previous one
        allow_workspace_cycles   = true,
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        disable_splash_rendering = true,
        focus_on_activate       = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },

    ecosystem = {
        no_update_news = true, -- Don't show update news on first launch
    },
})

-- Curves and animations, see https://wiki.hypr.land/configuring/core/animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1 },    { 0.32, 1 }  } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 }  } })
hl.curve("linear",         { type = "bezier", points = { { 0, 0 },       { 1, 1 }     } })
hl.curve("almostLinear",   { type = "bezier", points = { { 0.5, 0.5 },   { 0.75, 1.0 } } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0 },    { 0.1, 1 }   } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us,no",
        kb_options = "grp:alt_shift_toggle",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Applications
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd(terminal .. " -e nvim"), { description = "Neovim" })
hl.bind(mainMod .. " + B",         hl.dsp.exec_cmd(browser), { description = "Browser" })
hl.bind(mainMod .. " + T",         hl.dsp.exec_cmd(terminal .. " -e btop"), { description = "btop" })
hl.bind(mainMod .. " + D",         hl.dsp.exec_cmd(terminal .. " -e lazydocker"), { description = "lazydocker" })
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.exec_cmd(terminal .. " -e k9s"), { description = "k9s" })
hl.bind(mainMod .. " + G",         hl.dsp.exec_cmd(messenger), { description = "Signal" })

-- Clipboard
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy"), { description = "Clipboard history" })

-- See https://wiki.hypr.land/configuring/core/binds/ for more
hl.bind(mainMod .. " + return",    hl.dsp.exec_cmd(terminal), { description = "Terminal" })
hl.bind(mainMod .. " + C",         hl.dsp.window.close(), { description = "Close window" })
hl.bind(mainMod .. " + M",         hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"), { description = "Exit Hyprland" })
hl.bind(mainMod .. " + E",         hl.dsp.exec_cmd(fileManager), { description = "File manager" })
hl.bind(mainMod .. " + V",         hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen(), { description = "Fullscreen" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized" }), { description = "Maximize" })
hl.bind(mainMod .. " + SPACE",     hl.dsp.exec_cmd(menu), { description = "App launcher" })
hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo(), { description = "Pseudotile" })         -- dwindle
hl.bind(mainMod .. " + O",         hl.dsp.layout("togglesplit"), { description = "Toggle split" })   -- dwindle
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("hyprlock"), { description = "Lock screen" })

-- Screenshot
hl.bind(mainMod .. " + X",       hl.dsp.exec_cmd("hyprshot -m region"), { description = "Screenshot region" })
hl.bind(mainMod .. " + ALT + X", hl.dsp.exec_cmd("hyprshot -m window"), { description = "Screenshot window" })

-- Keybind cheatsheet from bind descriptions
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd(
    [[hyprctl -j binds | jq -r '.[] | select(.has_description) | ({"0":"","64":"SUPER","65":"SUPER+SHIFT","72":"SUPER+ALT"}[.modmask|tostring] // (.modmask|tostring)) as $m | "\($m) + \(.key)\t\(.description)"' | column -ts $'\t' | rofi -dmenu -i -p keys]]
), { description = "Show keybinds" })

hl.bind(mainMod .. " + Tab", hl.dsp.focus({ last = true }), { description = "Last window" })

-- Move focus with mainMod + arrow keys / vim keys
-- Move active window inside workspace with mainMod + SHIFT + vim keys
local directions = {
    { keys = { "left", "h" },  direction = "left" },
    { keys = { "right", "l" }, direction = "right" },
    { keys = { "up", "k" },    direction = "up" },
    { keys = { "down", "j" },  direction = "down" },
}
for _, d in ipairs(directions) do
    for _, key in ipairs(d.keys) do
        hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ direction = d.direction }))
    end
    hl.bind(mainMod .. " + SHIFT + " .. d.keys[2], hl.dsp.window.swap({ direction = d.direction }))
end

-- Resize mode: mainMod + R, then hjkl / arrows, Escape or Return to leave
hl.bind(mainMod .. " + R", hl.dsp.submap("resize"), { description = "Resize mode" })
hl.define_submap("resize", function()
    for _, d in ipairs({
        { keys = { "left", "h" },  x = -20, y = 0 },
        { keys = { "right", "l" }, x = 20,  y = 0 },
        { keys = { "up", "k" },    x = 0,   y = -20 },
        { keys = { "down", "j" },  x = 0,   y = 20 },
    }) do
        for _, key in ipairs(d.keys) do
            hl.bind(key, hl.dsp.window.resize({ x = d.x, y = d.y, relative = true }), { repeating = true })
        end
    end
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("return", hl.dsp.submap("reset"))
end)

-- Switch workspaces with mainMod + [0-9] / F1-F12
-- Move active window to a workspace with mainMod + SHIFT + [0-9] / F1-F12
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,            hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key,    hl.dsp.window.move({ workspace = i }))
end
for i = 1, 12 do
    hl.bind(mainMod .. " + F" .. i,             hl.dsp.focus({ workspace = 10 + i }))
    hl.bind(mainMod .. " + SHIFT + F" .. i,     hl.dsp.window.move({ workspace = 10 + i }))
end

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"), { description = "Toggle scratchpad" })
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }), { description = "Move to scratchpad" })
hl.bind(mainMod .. " + grave",     hl.dsp.focus({ workspace = "previous" }), { description = "Previous workspace" })

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl s 10%+"),                           { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"),                           { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/configuring/core/rules/

hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
